config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :invitados
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitado.rb
class Invitado < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invitados_controller.rb
class InvitadosController < ApplicationController
	def index
    	@invitados = Invitado.all
  	end
	def show
		@invitado = Invitado.find(params[:id])
  	end
	def new
	
	end
	def create
		
		 @invitado = Invitado.new(invitado_params)
		 @invitado.save
		 redirect_to @invitado
	end
	def destroy
		Invitado.destroy(params[:id])
		redirect_to invitados_path
	end
	private
  		def invitado_params
    	params.require(:invitado).permit(:nombre, :regalo)
  		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitados_helper.rb
module InvitadosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invitados/index.html.erb
<h1>Lista de invitados</h1>
 
<table>
  <tr>
    <th>Nombre</th>
    <th>Regalo</th>
  </tr>
 
  <% @invitados.each do |inv| %>
    <tr>
      <td><%= inv.nombre %></td>
      <td><%= inv.regalo %></td>
      <td><%= link_to 'Ver', invitado_path(inv) %></td>
      <td><%= link_to 'Borrar', 
                        invitado_path(inv), 
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Volver', controller: 'welcome' %>

app/views/invitados/new.html.erb
<h1>Registrar nuevo invitado</h1>
<%= form_for :invitado, url: invitados_path do |f| %>
  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </p>
 
  <p>
    <%= f.label :regalo %><br>
    <%= f.text_area :regalo %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %><br>
<%= link_to 'Volver', controller: 'welcome' %>

app/views/invitados/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @invitado.nombre %>
</p>
 
<p>
  <strong>Regalo:</strong>
  <%= @invitado.regalo %>
</p>
<%= link_to 'Volver', new_invitado_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matricidio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Lista de invitados 1.0</h1>
<%= link_to 'Lista de invitados', controller: 'invitados' %><br>
<%= link_to 'Registrar invitado', new_invitado_path %>